simulation:
  num_cell_types: 3
  cells_per_type: 50
  mask_size: 100
  min_distance: 0.2

distributions:
  type1:
    x: {loc: -1, scale: 0.5}
    y: {loc: -1, scale: 0.5}
  type2:
    x: {loc: 1, scale: 0.5}
    y: {loc: 1, scale: 0.5}
  type3:
    x: {loc: 0, scale: 0.5}
    y: {loc: 0, scale: 0.5}

interaction_matrix:
  - [1.0, 0.5, -0.3]
  - [0.5, 1.0, 0.2]
  - [-0.3, 0.2, 1.0]
